/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.hanborq.gravity.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum TState implements org.apache.thrift.TEnum {
  PENDING(1),
  RUNNING(2),
  PAUSED(3),
  ABORTED(4),
  COMPLETED(5);

  private final int value;

  private TState(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TState findByValue(int value) { 
    switch (value) {
      case 1:
        return PENDING;
      case 2:
        return RUNNING;
      case 3:
        return PAUSED;
      case 4:
        return ABORTED;
      case 5:
        return COMPLETED;
      default:
        return null;
    }
  }
}
